task 2 done
EvoMGenius/whitesoft-homeworks pull request #4
Opened 2022-05-23 19:21 UTC by EvoMGenius

2022-05-23 23:48 UTC, snusmum commented
Не хватает .gitignore в корне проекта. Не должны в репозиторий улетать .idea и target

2022-05-25 02:08 UTC, mv-shallow commented on task1/src/main/java/actions/SearchingUtils.java
> +    public List<Employee> search(List<Employee> employees, SearchParams params) {
Метод можно сделать статическим, тогда не нужно создавать класс и внедрять его в сервис

2022-05-25 02:08 UTC, mv-shallow commented on task1/src/main/java/actions/SearchingUtils.java
> +            predicateFirstName = employee -> employee.getFirstName().equals(params.getFirstName());
жесткий поиск, лучше toLower + contains

2022-05-25 02:08 UTC, mv-shallow commented on task1/src/main/java/actions/SearchingUtils.java
> +        Predicate<Employee> predicateFirstName = Objects::nonNull;
Не самый удачный вариант, можно обойтись одним предикатом и .filter

2022-05-25 02:08 UTC, mv-shallow commented on task1/src/main/java/models/Employee.java
> +//@ToString
Комменты из ПР лучше убирать

2022-05-25 02:08 UTC, mv-shallow commented on task1/src/test/java/services/EmployeeServiceTest.java
> +    List<Employee> employees = new ArrayList<>(List.of(new Employee("Иван", "Иванов", "", List.of("some characteristics"), new Post(UUID.fromString("854ef89d-6c27-4635-926d-894d76a81707"), "Backend S
Тестовые данные в отдельный файл(json)

2022-05-25 02:08 UTC, mv-shallow commented on task1/src/main/java/services/EmployeeService.java
> +    private List<Employee> employees = new ArrayList<>();
Почему не final?

2022-05-25 02:08 UTC, mv-shallow commented on task1/src/main/java/models/SearchParams.java
> +    private String firstName;
Можно через @FieldDefaults указать модификатор доступа

2022-05-25 02:08 UTC, mv-shallow commented on task1/src/main/java/models/Employee.java
> +    protected String firstName;
Для чего protected?

2022-05-25 08:07 UTC, EvoMGenius commented on task1/src/main/java/models/Employee.java
> +    protected String firstName;
это делалось с первого задания по диаграмме классов, которая была приложена в задании. и вроде там он не private, но и не public
поэтому решил что protected, хотя можно и чтобы дефолтный стоял

2022-05-28 02:27 UTC, progressicu requested changes

2022-05-28 02:27 UTC, progressicu commented on task1/src/main/java/models/Employee.java
> +    protected String firstName;
по умолчанию принимаем, что это private, т.к. когда public, то это явно указываем. Но согласен, это моя недоработка, не думал, что так можно подумать

2022-05-28 02:27 UTC, progressicu commented on task1/src/main/java/services/EmployeeService.java
> +@Getter
зачем это тут? Это сервис и он в себе инкапсулирует работу с сущностями.
Это пока тут список работников, но в дальнейшем это может быть и rest запросы, и бд и многое другое. И отдавать эти "способы" хранения плохой вариант.
Лучше работать через определенные методы. Если нужно вернуть всех работников, то создаешь такой метод и возвращаешь копию работников (в данном случае, если было бы бд, то доставал всех и т.д.)

2022-05-28 02:27 UTC, progressicu commented on task1/src/main/java/actions/SearchingUtils.java
> +        //очень долго думал как сделать, чтобы при отсутствии params вывод не страдал. Ибо выводил пустой лист
и зачем этот коммент? если нужна помощь, то пиши не в коде, а в группе/личке

2022-05-28 02:27 UTC, progressicu commented on task1/src/main/java/actions/SearchingUtils.java
> +        Predicate<Employee> predicateUUID = Objects::nonNull;
можно просто = emp -> true

2022-05-28 02:27 UTC, progressicu commented on task1/src/main/java/services/EmployeeService.java
> +    public Employee parseFromJson(JSONObject employee){
методы парсинга можно вынести в отдельный класс, а вот метод поиска можно было наоборот сюда. 
Т.к. при парсинге идет работа немного в другой плоскости (парсинг, json, regex, ...), а при поиске идёт работа чисто работниками

2022-05-28 02:27 UTC, progressicu commented on task1/src/main/java/services/EmployeeService.java
> +    public void autofillPosts(){ //создано для тестов
сервис с работниками отвечает за должности, не странная ли логика?

2022-05-30 22:22 UTC, progressicu approved these changes
Исправь последние комменты и можешь сливать. Хорошо получилось 👍

2022-05-30 22:22 UTC, progressicu commented on task1/src/main/java/services/EmployeeService.java
> +        Predicate<Employee> predicateFirstName = employee -> true;
можно было оставить один Predicate, просто потом в if к нему добавлять условия.
https://www.baeldung.com/java-predicate-chain

2022-05-30 22:22 UTC, progressicu commented on task1/src/test/java/services/EmployeeServiceTest.java
> +//    PostsService postsService = new PostsService();
Закоментированный код никогда не оставляем.
Если он не работает и его надо починить - чини, если он лишний - удали

2022-05-30 22:51 UTC, progressicu commented on task1/src/test/java/services/EmployeeServiceTest.java
> +    public void parseFromJsonFromFile() {
мы тестируем методы сервиса (раз EmployeeServiceTest называется класс).
Но в EmployeeService нет такого метода как parseFromJsonFromFile(). Этот тест больше на интеграционный похож и всё равно тоже непонятно что он проверяет. Всё подряд нельзя проверять

2022-05-31 19:26 UTC, merged