Task3
EvoMGenius/whitesoft-homeworks pull request #5
Opened 2022-06-07 04:13 UTC by EvoMGenius

2022-06-09 05:21 UTC, mv-shallow commented
По организации файлов :
- аргументы для действий должны лежать рядом с действиями;
- сервисы внутри пакета сервисов должны быть разделены по сущности(т.е. EmployeeService и PostService в отдельных пакетах);
- когда аргументов несколько, то их стоит положить в один пакет argument(s). Сам пакет следует располагать как можно ближе к классу, который использует данные аргументы

2022-06-09 05:21 UTC, mv-shallow commented
Где тесты?

2022-06-09 05:21 UTC, mv-shallow requested changes

2022-06-09 05:21 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/service/EmployeeService.java
> +        }
Можнл вынести в отдельный метод, который принимает две строки и приводит их к одному регистру + проверяет вхождение

2022-06-09 05:21 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/service/EmployeeService.java
> +        if(params.getFirstName()!=null){
Построение предиката уже можно вынести в отдельный метод

2022-06-09 05:21 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/repository/EmployeeRepository.java
> +    public Employee save(Employee employee) {
Вынеси проверки в сервис. Более того, разве эта проверка сработает? В коде не переопределен метод equals

2022-06-09 05:21 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/service/EmployeeService.java
> +    public List<Employee> getEmployees(){
Лишний метод?

2022-06-09 05:21 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/service/EmployeeService.java
> +    public List<Employee> getEmployeesWithSearchParams(SearchParams params) {
Можно назвать list, ведь если не указаны параметры, то он возвращает весь список

2022-06-09 05:21 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/action/UpdateEmployeeAction.java
> +                        new IllegalPostIdException(String.format("Incorrect postID - %s", argument.getPostId().toString()))
Странное описание ошибки. Почему некорректный id? Не найдена должность.

2022-06-11 07:10 UTC, progressicu requested changes

2022-06-11 07:10 UTC, progressicu commented on task1/src/main/java/com/evo/apatios/controller/EmployeeController.java
> +    @GetMapping()
просто getMapping не пойдет. Т.к. в таком случае будет запрос "/employee", т.е. по названию это один работник, а не несколько

2022-06-11 07:10 UTC, progressicu commented on task1/src/main/java/com/evo/apatios/service/EmployeeService.java
> +        Guard.check(employee.getId()==null, "Employee Id must be null", CreationEmployeeException::new);
id вручную в коде пока генерим. Клиент не должен это передавать в дто или ещё как

2022-06-11 07:10 UTC, progressicu commented on task1/src/main/java/com/evo/apatios/service/EmployeeService.java
> +                .filter(predicates.stream().reduce(x->true , Predicate::and))
переделать говорил на занятии на более простой вариант

2022-06-11 07:10 UTC, progressicu commented on task1/src/main/java/com/evo/apatios/service/PostService.java
> +public class PostService {
а почему тут и в контролере нет методов для обновления и удаления?

2022-06-28 05:30 UTC, mv-shallow requested changes
Интеграционные тесты на контроллеры планируются?

2022-06-28 05:30 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/action/CreationEmployeeAction.java
> +public class CreationEmployeeAction {
Тогда уж EmployeeCreationAction, не? А вообще обычно называем CreateEmployeeAction

2022-06-28 05:30 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/controller/employee/EmployeeController.java
> +    @GetMapping("/all")
Так все или всё-таки те, которые соответствуют критериям поиска? Точнее будет list

2022-06-28 05:30 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/controller/employee/EmployeeController.java
> +        return employeeMapper.entityToDto(employeeService.findById(id).orElseThrow(NotFoundEmployeeException::new));
Исключение стоит кидать прямо в сервисе, под это можно завести отдельный метод getExisting

2022-06-28 05:30 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/controller/employee/EmployeeController.java
> +                creationEmployeeAction.execute(
Лучше без вложенных вызовов, так легче читать

2022-06-28 05:30 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/controller/employee/EmployeeController.java
> +    @ResponseStatus(HttpStatus.OK)
И без этого будет OK

2022-06-28 05:30 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/controller/employee/mapper/EmployeeMapper.java
> +public class EmployeeMapper {
Почему не используешь библиотеки для маппинга?

2022-06-28 05:30 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/controller/employee/EmployeeController.java
> +                                  @Validated(New.class) EmployeeDto employeeDto){
На вход отдельный класс, в данном случае должен быть CreateEmployeeDto

2022-06-28 05:30 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/dto/EmployeeDto.java
> +    @Null(groups = {New.class})
Перебор. С разделением DTO на входящие и исходящие группы валидации вообще не понадобятся

2022-06-28 05:30 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/dto/EmployeeDto.java
> +    private Contacts contacts;
Dto

2022-06-28 05:30 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<MessageError> catchIllegalPostNameException(NotFoundPostException e){
Статус через ResponseStatus, так проще

2022-06-28 05:30 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/exception/MessageError.java
> +    private int status;
Статус уже есть в самом ответе из сервиса, лишнее

2022-06-28 05:30 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/model/Employee.java
> +@Data
Тянет за собой EqualsAndHashCode, не рекомендуется использовать для сущностей
https://thorben-janssen.com/lombok-hibernate-how-to-avoid-common-pitfalls/#Don8217t_Use_EqualsAndHashCode

2022-06-28 05:30 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/service/employee/EmployeeService.java
> +        return repository.save(Employee.builder()
Здесь лучше получить **cуществующего** сотрудника по id, обновить его параметры через set... , а потом сохранить. Это больше подходит к обновлению записи и добавляет проверку на то, что сотрудник действительно обновляется, а не создается с нуля

2022-06-28 05:30 UTC, mv-shallow commented on task1/src/test/java/com/evo/apatios/service/employee/EmployeeServiceTest.java
> +
без пустых строк здесь, а между блоками стоит делать пустую строку, да

2022-06-28 05:30 UTC, mv-shallow commented on task1/src/test/java/com/evo/apatios/service/employee/EmployeeServiceTest.java
> +        Assertions.assertArrayEquals(employeeList.toArray(), List.of(Employee.builder()
Почему сравниваешь именно массивы?

2022-06-28 05:30 UTC, mv-shallow commented on task1/src/test/java/com/evo/apatios/service/employee/EmployeeServiceTest.java
> +        CreationEmployeeAgrument argument = CreationEmployeeAgrument.builder()
не хватает пустой строки

2022-07-01 07:41 UTC, EvoMGenius commented
Остались интеграционные тесты и тесты для базы данных. Они в процессе написания

2022-07-01 09:29 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<MessageError> catchNotFoundPostException(NotFoundPostException e){
Писал об этом [ранее](https://github.com/EvoMGenius/whitesoft-homeworks/pull/5#discussion_r893071902). Зачем здесь ResponseEntity, если статус ты уже указываешь через аннотацию?

2022-07-01 09:29 UTC, mv-shallow commented on task1/src/main/resources/application.properties
> +spring.datasource.username=postgres
А такое раскрывать не нужно, как и путь к базе) https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.files.property-placeholders

2022-07-03 04:42 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/exception/NotFoundException.java
> +        if (className != null) sb.append("\"className\": \"").append(className).append("\", ");
А для чего тогда stacktrace?)

2022-07-03 04:42 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/model/Employee.java
> +        return Objects.equals(id,employee.getId()) && Objects.equals(post, employee.getPost());
Зачем оставил должность?

2022-07-03 04:42 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/service/employee/EmployeeService.java
> +        Employee existedEmployee = repository.findById(id).orElseThrow(()-> new NotFoundException("Employee.class","Employee with this id is not found", id));
Думаю, клиенту понятно, что не найден именно сотрудник, потому что в сообщении об этом и написано, класс лишний

2022-07-03 04:42 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/service/employee/EmployeeService.java
> +        Employee existedEmployee = repository.findById(id).orElseThrow(()-> new NotFoundException("Employee.class","Employee with this id is not found", id));
У тебя уже есть метод под это - getExisting

2022-07-03 05:10 UTC, EvoMGenius commented on task1/src/main/java/com/evo/apatios/exception/NotFoundException.java
> +        if (className != null) sb.append("\"className\": \"").append(className).append("\", ");
ну чтобы был) убрать это?

2022-07-03 05:18 UTC, EvoMGenius commented on task1/src/main/java/com/evo/apatios/model/Employee.java
> +        return Objects.equals(id,employee.getId()) && Objects.equals(post, employee.getPost());
читал вот эту [статью](https://thorben-janssen.com/ultimate-guide-to-implementing-equals-and-hashcode-with-hibernate/) и видимо не совсем правильно понял момент где используется NaturalId. и смутился немного видимо. у нас то объекты всегда уникальны по id будут. так что да. исправлю

2022-07-03 05:50 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/exception/NotFoundException.java
> +        if (className != null) sb.append("\"className\": \"").append(className).append("\", ");
"ну чтобы был" - с такой формулировкой можно много что сделать) Да, лучше убрать. Тем более, ты здесь собираешь json. То же самое будет, если вызвать objectMapper.writeValueAsString. Клиент уже получит автоматически сформированный json, а если с исключением будут работать в сервисе, то информацию получат через геттеры

2022-07-03 06:07 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/model/Employee.java
> +        return Objects.equals(id,employee.getId()) && Objects.equals(post, employee.getPost());
https://docs.jboss.org/hibernate/orm/5.0/mappingGuide/en-US/html/ch07.html

NaturalId, как и следует из названия - естественный идентификатор. Т.е. у нас есть идентификатор системный (id), а у хранимого объекта также есть свойство(атрибут), который позволяет нам его идентифицировать. Пример прямо в статье - у компании есть ИНН, а значит в системе её можно однозначно найти или по внутреннему id, или по ИНН. Во время работы с данными через Spring Data JPA преимуществ нет, поэтому можно её не указывать.

2022-07-03 12:45 UTC, progressicu reviewed
Не нужно было закидывать работу с БД в это ПР. В итоге просто получилось, что ни контроллеры, ни тесты, ни бд до конца ещё не сделаны, а так бы скорее всего уже было всё готово.
Инициатива это хорошо, но нужно уметь ею пользоваться. Если у тебя стоит задача сделать что-то в срок, но в итоге ты делаешь другое, а то что нужно делаешь не до конца, то это выглядит не очень. Нужно было сначала закончить то что нужно, а потом добавлять новое и было бы замечательно.

Но если не брать это в рассчет, то вообще молодец 👍

2022-07-03 12:45 UTC, progressicu commented on task1/pom.xml
> +<!--        <dependency>-->
комменты удаляем, для чего они тут

2022-07-03 12:45 UTC, progressicu commented on task1/pom.xml
> +            <artifactId>lombok-mapstruct-binding</artifactId>
это тут не нужно. Оно нужно только на этапе компиляции

2022-07-03 12:45 UTC, progressicu commented on task1/src/main/java/com/evo/apatios/controller/post/PostController.java
> +    @GetMapping("/all")
почему не /list ? Нужно чтобы везде прослеживалось единообразие. Это позволяет быстрее писать код, т.к. не надо задумываться над стандартными вещами

2022-07-03 12:45 UTC, progressicu commented on task1/src/main/java/com/evo/apatios/controller/post/PostController.java
> +    @PutMapping
Нужно использовать PathVariable при обновлении и прочих действиях с объектом. Это одна из вещей в архитектуре REST

2022-07-03 12:45 UTC, progressicu commented on task1/src/main/java/com/evo/apatios/dto/input/post/CreatePostDto.java
> +public class CreatePostDto {
Пустой класс?

2022-07-03 12:45 UTC, progressicu commented on task1/src/main/java/com/evo/apatios/model/Employee.java
> +    public boolean equals(Object o) {
поддерживаю. Тут ещё нужно учесть что if(getClass() != o.getClass()) может вернуть true, т.к. может так получиться что один объект был прокси, а другой уже проинициализированный. Так что тут лучше действительно сравнивать по id и получить его через getter.

Хороший вариант показан здесь - https://vladmihalcea.com/the-best-way-to-implement-equals-hashcode-and-tostring-with-jpa-and-hibernate/ в классе Post

2022-07-03 12:45 UTC, progressicu commented on task1/src/main/java/com/evo/apatios/model/Post.java
> +@Entity
поправь форматирование везде. Ладно в одном месте, но у тебя то тут, то там где-то что-то поплыло. 
Не критично, но в глаза бросается

2022-07-03 12:45 UTC, progressicu commented on task1/src/main/java/com/evo/apatios/model/Post.java
> +    @Id
Если я не ошибаюсь, то можно просто

    @Id
    @GeneratedValue
    private UUID id;

2022-07-03 12:45 UTC, progressicu commented on task1/src/main/java/com/evo/apatios/model/Employee.java
> +    private JobType jobType;
'@Enumerated(String)'

2022-07-03 12:45 UTC, progressicu commented on task1/src/main/java/com/evo/apatios/service/employee/EmployeeService.java
> +        existedEmployee.setAllFields(employee);
nit (на своё усмотрение решай как делать, просто высказываю своё мнение на это):
а чтобы проставить просто пару полей, будешь тоже в модели создавать новые методы?
Тут конечно можно пофилософствовать, что лучше, но как по мне модель это как дто но для бд. Оно просто хранит данные и имеет методы только в определенных случаях (для уменьшения копипасты, PrePersist,... )

2022-07-03 12:45 UTC, progressicu commented on task1/src/test/java/com/evo/apatios/action/CreateEmployeeActionTest.java
> +    void executeCreationWithExistingPost() {
тебе нужно разобраться что ты хочешь проверить и с какой целью. Это позволит быстрее писать код и он будет полезнее

Что ты делаешь сейчас:
Блок arrange:
- Создаешь аргумент - ок
- Создаешь должность - зачем, если можно было мок? Тебе же главное проверить, что в аргумент создания работника передалось то, что взялось из postService.getExistingById
- мокаешь вызов postService.getExistingById - ок
- мокаешь вызов employeeService.create - зачем возвращаешь работника, если можно мок? Ты же в Action сразу возвращаешь этого работника, действий с ним никаких не производишь. Значит тут можно вернуть мок и потом просто проверяем что мок, который вернули с помощью when(employeeService.create()) действительно тот же, что и из action.execute(argument)

Блок assert:
- Проверяешь что из action-a вернулось правильное значение - Учтем пунтк выше и тут будет всего одна строка кода
- проверяешь verify(employeeService).create(any()) - ты это уже проверил, когда писал when(employeeService.create(any())).thenReturn(). Если этот when выполнился и что-то вернулось, то смысл здесь ещё раз проверять, что это вызвалось? **А вот проверить что туда передалось нужно, т.к. в этом и есть суть этого теста**. Это можно сделать через ArgumentCaptor
- verify(postService).getExistingById(postId); - тоже лишено смысла проверять это по аналогии с пунктом выше, ты уже в arrange по факту проверил, что вызов должен произойти с этим postId

2022-07-03 12:45 UTC, progressicu commented on task1/src/test/java/com/evo/apatios/action/CreateEmployeeActionTest.java
> +    void executeCreationWithExistingPost() {
примени эти рассуждения к другим тестам

2022-07-03 20:59 UTC, EvoMGenius commented on task1/src/main/java/com/evo/apatios/service/employee/EmployeeService.java
> +        existedEmployee.setAllFields(employee);
ну я долго думал, что можно просто присвоить через сеттеры. но подумал, что так более компактно и читабельно будет. можно куда-нибудь перенести этот метод наверное, либо все же стоит убрать?

2022-07-03 22:11 UTC, EvoMGenius commented on task1/src/main/java/com/evo/apatios/model/Post.java
> +@Entity
Поправлю. Просто я периодически то с ноутбука пишу, то с компьютера. и на ноутбуке idea подсвечивает где и сколько раз поля упоминаются, и это создает доп пространство между строками. поэтому так ломано выглядит.

2022-07-04 01:26 UTC, progressicu commented on task1/src/main/java/com/evo/apatios/service/employee/EmployeeService.java
> +        existedEmployee.setAllFields(employee);
просто здесь оставить присвоение через сеттеры, это нормальное поведение

2022-07-10 17:49 UTC, EvoMGenius commented
Возможно дабы соблюдать структуру того, что id при update передается вплоть до сервиса, нужно будет переделать чтобы action вызывал update у сервиса с передачей туда id. напишите пожалуйста если так следует сделать

2022-07-11 07:52 UTC, mv-shallow requested changes

2022-07-11 07:52 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/action/UpdateEmployeeAction.java
> +    public Employee execute(UUID id, UpdateEmployeeActionArgument employeeArgument) {
Можно было и так оставить, тоже было хорошо.

2022-07-11 07:52 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/exception/CreationEmployeeException.java
>          this.errorMessage = "CREATION EMPLOYEE EXCEPTION";
Можно заполнять message в RuntimeException

2022-07-11 07:52 UTC, mv-shallow commented on task1/src/main/java/com/evo/apatios/exception/MessageError.java
> +        this.timestamp = LocalDateTime.now();
? timestamp

2022-07-11 07:52 UTC, mv-shallow commented on task1/src/test/java/com/evo/apatios/controller/employee/EmployeeControllerTest.java
> +        EmployeeDto expected = EmployeeDto.builder()
А что с форматированием? Разве вам не кидали файл с настройками для IDE?
Ожидаемые данные не в Arrange

2022-07-11 07:52 UTC, mv-shallow commented on task1/src/test/java/com/evo/apatios/controller/employee/EmployeeControllerTest.java
> +    void findAllEmployeesWithSearchParams() {
Когда есть поиск с опиональными параметрами стоит написать параметризованный тест

2022-07-11 07:52 UTC, mv-shallow commented on task1/src/test/java/com/evo/apatios/controller/employee/EmployeeControllerTest.java
> +    void updateNotExisted() {
Лишний тест. По факту проверяется метод getExisting, а ты его уже проверил выше

2022-07-11 07:52 UTC, mv-shallow commented on task1/src/test/resources/dataset/EmployeeControllerTest/create/DB.json
> +    {
Можно без этих скобок

2022-07-15 14:12 UTC, progressicu commented on task1/src/test/java/com/evo/apatios/service/employee/EmployeeServiceTest.java
> +    void create() {
я это же ещё говорил здесь https://github.com/EvoMGenius/whitesoft-homeworks/pull/5/files#r912480935

2022-07-15 14:14 UTC, progressicu commented on task1/src/test/java/com/evo/apatios/controller/employee/EmployeeControllerTest.java
> +                                                               .characteristics(new ArrayList<>())
Почему характеристики не задаешь? 
Тесты должны быть полные. Нужно проверять все поля.
Аналогично при обновлении, нужно обновлять все поля

2022-07-15 14:42 UTC, EvoMGenius commented on task1/src/test/java/com/evo/apatios/service/employee/EmployeeServiceTest.java
> +    void create() {
Видимо не так понял. Хорошо, все исправлю)

2022-07-17 14:25 UTC, EvoMGenius commented
nit. возникли небольшие трудности с тестом сервиса на получение списка работников с параметрами. не придумал ничего лучше чем через argumentCaptor проверить как передается предикат. возможно лишено смысла. если что скажите, исправлю.

2022-07-18 00:48 UTC, progressicu reviewed
в целом отлично, правь эти мелочи, я потом их гляну и сольем

2022-07-18 00:48 UTC, progressicu commented on task1/src/main/java/com/evo/apatios/dto/output/employee/EmployeeDto.java
> +    private UUID postId;
почему тут postId, а не PostDto? Фронту/мобилке в таком случае нужно будет постоянно дополнительно запрашивать и должности, а т.к. при начале загрузки страницы этот id ещё неизвестен, то запросы придется делать последовательно, что не очень хорошо

2022-07-18 00:48 UTC, progressicu commented on task1/src/main/java/com/evo/apatios/service/employee/EmployeeService.java
> +//import java.util.function.Predicate;
?

2022-07-18 00:48 UTC, progressicu commented on task1/src/main/java/com/evo/apatios/service/employee/EmployeeService.java
> +        return Lists.newArrayList(repository.findAll(predicate != null ? predicate
А он у тебя может быть null? Вроде ExpressionUtils.allOf не возвращает null

2022-07-18 00:48 UTC, progressicu commented on task1/src/test/java/com/evo/apatios/action/CreateEmployeeActionTest.java
> +        //act
как-то всё в кучу налеплено

2022-07-18 00:48 UTC, progressicu commented on task1/src/test/java/com/evo/apatios/action/CreateEmployeeActionTest.java
> +        when(employeeService.create(employeeArgumentCaptor.capture())).thenReturn(expectedEmployee);
лучше всего создание captor-а, "внедрение" его в метод (через verify) и получение делать в assert, т.к. ты это же уже проверка

2022-07-18 00:48 UTC, progressicu commented on task1/src/test/java/com/evo/apatios/action/CreateEmployeeActionTest.java
> +                                            .ignoringFields("postId", "post")
ок, а где тогда проверка post?

2022-07-18 00:48 UTC, progressicu commented on task1/src/test/java/com/evo/apatios/service/employee/EmployeeServiceTest.java
> +        assertThat(capturedPredicate).isEqualTo(expectedPredicate);
можно было перехватить предикат как ты сделал и потом проверить через Assertions.assertThat(capturedPredicate).hasToString(иТутОжидаемоеУсловиеТекстом)
Так довольно удобно и меньше места занимаем

2022-07-18 04:55 UTC, EvoMGenius commented on task1/src/main/java/com/evo/apatios/service/employee/EmployeeService.java
> +        return Lists.newArrayList(repository.findAll(predicate != null ? predicate
как выяснилось он может быть null-ом. в ручную тестил когда. если не вводить вообще параметры, пишет, что Predicate не может быть null

2022-07-18 05:05 UTC, EvoMGenius commented on task1/src/test/java/com/evo/apatios/service/employee/EmployeeServiceTest.java
> +        assertThat(capturedPredicate).isEqualTo(expectedPredicate);
думал о таком. но как-то подумал что это через чур хардкод. хорошо, сделаю

2022-07-21 13:32 UTC, progressicu approved these changes

2022-07-21 13:46 UTC, merged