Aspects logger task
EvoMGenius/whitesoft-homeworks pull request #6
Opened 2022-07-24 20:38 UTC by EvoMGenius

Сделал логирование через аспекты. Чуток подправил pom.

nit добавил отдельно guava. ибо она находится в зависимостях другой зависимости, которая мне нужна только для тестов.

2022-07-25 08:38 UTC, snusmum requested changes
Необходимо добавить аспектам юнит-тесты.

Под * можно в интеграционных тестах контроллера проверить запись в лог, перехватив сообщения логгеру.

2022-07-25 08:38 UTC, snusmum commented on task1/src/main/java/com/evo/apatios/util/aspect/ControllersMethodLoggingAspect.java
> +    @Pointcut("within(com.evo.apatios.controller.employee.EmployeeController) || within(com.evo.apatios.controller.post.PostController)")
Придётся помнить для каждого нового контроллера добавить строчку. Если ставить поинткат на пакет, исключив ненужные мапперы, то доработки больше не потребуются.

2022-07-25 08:38 UTC, snusmum commented on task1/src/main/java/com/evo/apatios/util/aspect/ControllersMethodLoggingAspect.java
> +    }
Не было в задании

2022-07-25 08:38 UTC, snusmum commented on task1/src/main/java/com/evo/apatios/util/aspect/ControllersMethodLoggingAspect.java
> +    }
Это всё будет размазано по логам.
Выделить конечно можно будет по имени пакета, но зачем такие сложности и пачка независимых выводов в консоль?
Нужно собирать одно сообщение со всей необходимой информацией, а потом один раз выводить его.
Можно завести вспомогательный класс, который будет переваривать HttpServletRequest и выдавать нужное сообщение.

2022-07-25 08:38 UTC, snusmum commented on task1/src/main/java/com/evo/apatios/util/aspect/UpdateEmployeeMethodLoggingAspect.java
> +        }
тоже нужно выводить одно сообщение

2022-07-25 08:38 UTC, snusmum commented on task1/src/main/java/com/evo/apatios/util/aspect/UpdateEmployeeMethodLoggingAspect.java
> +    @Pointcut("execution(public * com.evo.apatios.service.employee.EmployeeService.update(..))")
Можно было бы завести аннотацию, т.к. жёстко привязано к методу и аргументу.

2022-07-25 08:38 UTC, snusmum commented on task1/src/test/java/com/evo/apatios/service/employee/argument/EmployeeArgumentProvider.java
> +    }
Это можно размещать в том же тестовом классе, т.к. не требуется для других.
Также можно заменить на methodSource, который будет возвращать список Arguments.

2022-07-25 15:24 UTC, EvoMGenius commented on task1/src/main/java/com/evo/apatios/util/aspect/ControllersMethodLoggingAspect.java
> +    @Pointcut("within(com.evo.apatios.controller.employee.EmployeeController) || within(com.evo.apatios.controller.post.PostController)")
Почитав немного документации и народным методом тыка выяснилось,что достаточно будет написать "within(com.evo.apatios.controller.*.*Controller)". мапперы не затронутся. а затронутся все классы заканчивающиеся на Controller находящиеся в подпакете пакета controller. собственно для меня то что нужно. если все же нет, то напишите, сделаю так как вы говорите

2022-07-26 13:04 UTC, EvoMGenius commented
Осталось написать тесты на аспекты

2022-07-27 00:32 UTC, snusmum commented on task1/src/main/java/com/evo/apatios/util/aspect/ControllersMethodLoggingAspect.java
> +    @Pointcut("within(com.evo.apatios.controller.employee.EmployeeController) || within(com.evo.apatios.controller.post.PostController)")
Тоже хороший вариант.

2022-07-27 22:24 UTC, EvoMGenius commented
юнит тесты то впринципе готовы. но я не совсем понимаю как сделать перехват сообщения в логгер. плюс еще хотел проверить что логгер получает в аспекте в юнит тестах. так и не придумал адекватного способа того, как мне вытащить мок логгера, ибо логгер обычно автоматически присваивается в поле класса через фабрику(собственно @Slf4j именно такой код и генерит) и вытащить мок не знаю как.

2022-07-28 01:41 UTC, snusmum commented
Для юнит-тестов можно воспользоваться [этой](https://www.simplify4u.org/slf4j-mock/) библиотекой. Но нужно будет немного поправить тест + в pom придётся для тестов отключить logback через maven-surefire-plugin.
Другой вариант (вполне допустимый) для тестирования - писать код так, чтобы текст для логгера возвращался из pacage-private метода. Тогда его можно будет проверить в тесте.  
А ещё можно мокать класс Appender и добавлять его в LoggerFactory для корневого логгера. Так можно и в интеграционных отыскать, что было записано в лог.

2022-07-28 01:44 UTC, snusmum commented on task1/src/test/java/com/evo/apatios/service/employee/EmployeeServiceTest.java
> +    void getEmployeeListWithAllCompletedSearchParams(SearchParams searchParams) {
И всё нормально компилируется и тесты проходят? В pom.xml не нашлось того, без чего не могут генерироваться Q-классы.

2022-07-28 01:46 UTC, snusmum commented on task1/src/main/java/com/evo/apatios/util/aspect/ApiRequestLoggingAspect.java
> +package com.evo.apatios.util.aspect;
Обычно аспекты не в утилях, а на верхнем уровне наравне с моделями и т.п.
Но сейчас не принципиально.

2022-07-28 01:49 UTC, snusmum commented on task1/src/main/java/com/evo/apatios/util/aspect/UpdateEmployeeMethodLoggingAspect.java
> +        }
Все блоки if очень походи, можно было бы вынести код в отдельный метод, передавая имя поля и значения.

2022-07-28 03:08 UTC, EvoMGenius commented on task1/src/test/java/com/evo/apatios/service/employee/EmployeeServiceTest.java
> +    void getEmployeeListWithAllCompletedSearchParams(SearchParams searchParams) {
да. все компилируется, тесты запускаются, все работает. я сгенерил Q-классы и удалил зависимость эту, чтоб не разростать pom. врядли сущности будут уже меняться, ну а если будут, то заново подключу и перегенерю.

2022-07-28 03:11 UTC, EvoMGenius commented on task1/src/main/java/com/evo/apatios/util/aspect/ApiRequestLoggingAspect.java
> +package com.evo.apatios.util.aspect;
перенесу, но как тогда пакет назвать? аспекты? или конкретно по целевому назначению - logging ?

2022-07-28 06:45 UTC, snusmum commented on task1/src/main/java/com/evo/apatios/util/aspect/ApiRequestLoggingAspect.java
> +package com.evo.apatios.util.aspect;
Сейчас не нужно. Просто для информации.

2022-07-28 06:45 UTC, snusmum commented on task1/src/test/java/com/evo/apatios/service/employee/EmployeeServiceTest.java
> +    void getEmployeeListWithAllCompletedSearchParams(SearchParams searchParams) {
Нужно вернуть. Проект должен собираться где угодно.

2022-07-28 20:04 UTC, EvoMGenius commented
В процессе написания тестов...

2022-07-29 10:44 UTC, EvoMGenius commented
Пока не осилил юнит тест для аспекта логирующего запросы к контроллерам.

2022-07-29 11:19 UTC, EvoMGenius commented
Пока не додумался как именно можно сделать через slf4j-mock библеотеку и отключение logback через maven-surefire-plugin. потратил на это практически весь день - безуспешно. Поэтому решил через appender сделать.

2022-07-30 12:16 UTC, snusmum requested changes
В целом норм. Необходимо почистить код и поправить ошибки.
Из тестов точно нужно добавить проверку логгирования обновления в контроллере.
Если успеешь ещё и тесты аспекта улучшить, то будет совсем замечательно.

2022-07-30 12:16 UTC, snusmum commented on task1/src/main/java/com/evo/apatios/aspect/logging/UpdateEmployeeMethodLoggingAspect.java
> +        }
Речь была о том, чтобы добавить что-то вроде этого
![image](https://user-images.githubusercontent.com/41713164/181911594-af928f29-c484-45f8-bfcf-80559bbd0a90.png)
Тогда в методе выше будут только строчки из append и никаких проверок.

2022-07-30 12:16 UTC, snusmum commented on task1/src/main/java/com/evo/apatios/aspect/logging/UpdateEmployeeMethodLoggingAspect.java
> +        }
Это должно помочь завести либу для тестов.
![image](https://user-images.githubusercontent.com/41713164/181912224-2df48185-c1e0-45a8-abcf-32bb048b3903.png)

Но не обязательно. Аппендером можно было бы и здесь пользоваться.
Или protected методами.

Если бы тесты были (не обязательно через проверку вызова log), то поймал бы ошибку в  проверке, связанной с этим полем.

2022-07-30 12:16 UTC, snusmum commented on task1/src/main/java/com/evo/apatios/aspect/logging/annotation/Log.java
> +public @interface Log {
Такие аннотации делаются для конкретных целей и называть надо в соответствии с назначением.

2022-07-30 12:16 UTC, snusmum commented on task1/src/test/java/com/evo/apatios/controller/employee/EmployeeControllerTest.java
> +        assertApiRequestLog("EmployeeDto", "update", "UUID,UpdateEmployeeDto", expectedDto.getId().toString() + ", " + updateEmployeeDto, ip, endpoint, "PUT");
Проверка на обновление по терялась.

2022-07-30 12:16 UTC, snusmum commented on task1/src/test/java/com/evo/apatios/controller/employee/EmployeeControllerTest.java
>          EmployeeDto response = webTestClient.put()
Внезапно. Обычно post. Но менять уже не надо.

2022-07-30 12:16 UTC, snusmum commented on task1/src/test/java/com/evo/apatios/controller/employee/EmployeeControllerTest.java
> +//    delete - method= void com.evo.apatios.controller.employee.EmployeeController.deleteById(UUID), params= [ad4faaaf-1c1c-4442-87db-1df09c662f89], request: ipAddress= 127.0.0.1, endpoint= /employee
Много лишнего.

2022-07-30 18:54 UTC, EvoMGenius commented on task1/src/test/java/com/evo/apatios/controller/employee/EmployeeControllerTest.java
> +//    delete - method= void com.evo.apatios.controller.employee.EmployeeController.deleteById(UUID), params= [ad4faaaf-1c1c-4442-87db-1df09c662f89], request: ipAddress= 127.0.0.1, endpoint= /employee
да, не заметил, после почти 20 часов озадачивания этим таском и коддингом, даже не заметил. щас просмотрел еще, есть пару методов с ошибками в названии и прочие подобные ошибки

2022-07-30 18:57 UTC, EvoMGenius commented on task1/src/main/java/com/evo/apatios/aspect/logging/UpdateEmployeeMethodLoggingAspect.java
> +        }
да, как раз была ошибка класс каста.

2022-07-31 14:29 UTC, snusmum approved these changes

2022-07-31 14:29 UTC, snusmum commented on task1/src/main/java/com/evo/apatios/aspect/logging/UpdateEmployeeMethodLoggingAspect.java
> +                    getUpdateField(employeeBeforeUpdate.getCharacteristics(), employeeAfterUpdate.getCharacteristics(), "characteristics");
При таком количестве лучше уж билдер.

2022-07-31 22:02 UTC, EvoMGenius commented on task1/src/main/java/com/evo/apatios/aspect/logging/UpdateEmployeeMethodLoggingAspect.java
> +                    getUpdateField(employeeBeforeUpdate.getCharacteristics(), employeeAfterUpdate.getCharacteristics(), "characteristics");
Получается я уже могу сливать ветки? или нужно ждать аппрува от Гены?

2022-07-31 23:53 UTC, snusmum commented on task1/src/main/java/com/evo/apatios/aspect/logging/UpdateEmployeeMethodLoggingAspect.java
> +                    getUpdateField(employeeBeforeUpdate.getCharacteristics(), employeeAfterUpdate.getCharacteristics(), "characteristics");
Можешь сливать.

2022-08-01 03:49 UTC, merged